/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: hurkomendiguren (https://sketchfab.com/hurkomendiguren)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/azeria-6d4aff07356e409396872111bc97858f
title: Azeria
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/fox.gltf')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[8.88, -8.5, -0.67]} rotation={[-1.55, 0.01, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes.GLTF_created_0_rootJoint} />
          <skinnedMesh
            geometry={nodes.Object_7.geometry}
            material={materials.fox_material}
            skeleton={nodes.Object_7.skeleton}
          />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fox.gltf')
